# Generated by Django 3.2.5 on 2021-07-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('tipo', models.CharField(max_length=150)),
                ('preço', models.CharField(max_length=10)),
            ],
        ),
    ]
